name: Scheduled Terraform Drift Detection

on:
  workflow_dispatch:
  # schedule:
  #   # Run this workflow at the top of every hour
  #   - cron: "0 * * * *"

jobs:
  drift-detection:
    name: Detect and reconcile drift in Terraform stacks

    permissions:
      id-token: write
      contents: read
      pull-requests: read
      checks: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Terramate
        uses: terramate-io/terramate-action@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Terraform with asdf
        run: |
          asdf plugin add terraform
          asdf install terraform

      - name: Run Terraform init in all stacks
        run: |
          terramate script run \
            -C stacks \
            --parallel 1 \
            init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run drift detection
        id: drift-detect
        run: |
          terramate script run \
            -C stacks \
            --parallel 5 \
            --continue-on-error \
            -- \
            drift detect
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run drift reconciliation
        id: drift-reconcile
        run: |
          terramate script run \
            -C stacks \
            --tags reconcile \
            --status=drifted \
            --parallel 5 \
            --continue-on-error \
            -- \
            drift reconcile
        env:
          GITHUB_TOKEN: ${{ github.token }}
