name: Terraform Preview

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    name: Plan Terraform changes in changed stacks
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Terramate
        uses: terramate-io/terramate-action@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Terraform with asdf
        run: |
          asdf plugin add terraform
          asdf install terraform

      - name: Check Terramate formatting
        run: terramate fmt --check

      - name: Check Terraform formatting
        run: terraform fmt -recursive -check -diff

      - name: List changed stacks
        id: list-changed
        run: terramate list -C stacks --changed

      - name: Run Terraform init in all changed stacks
        if: steps.list-changed.outputs.stdout
        run: |
          terramate script run \
            -C stacks \
            --changed \
            --parallel 1 \
            init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Plan Terraform changes in changed stacks
        if: steps.list-changed.outputs.stdout
        run: |
          terramate script run \
            -C stacks \
            --changed \
            --parallel 5 \
            --continue-on-error \
            preview
        env:
          GITHUB_TOKEN: ${{ github.token }}
            
      - name: Generate Preview Comment
        if: steps.list-changed.outputs.stdout
        id: comment
        run: |
          echo >>pr-comment.txt "### List of Changed Stacks"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```bash'
          echo >>pr-comment.txt "${{ steps.list-changed.outputs.stdout }}"
          echo >>pr-comment.txt '```'
          echo >>pr-comment.txt "<details>"
          echo >>pr-comment.txt "<summary>Terraform Plan</summary>"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```terraform'
          terramate run --changed -- terraform show -no-color out.tfplan 2>&1 | dd bs=1024 count=248 >>pr-comment.txt
          echo >>pr-comment.txt '```'
          echo >>pr-comment.txt "</details>"
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      - name: Inform about no Changed Stacks
        if: (!steps.list-changed.outputs.stdout)
        run: |
          echo >>pr-comment.txt '### No changed stacks.'
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      - name: Publish Plans for Changed Stacks
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: terraform-plan
          path: pr-comment.txt